drone:  
  model_name: "hummingbird"

sensor:
  lidar_range: 4.
  # Match vertical FOV to camera (~50 deg total)
  lidar_vfov: [-25., 25.] # degree
  lidar_vbeams: 4 # Reduced from 6 to 4 for VRAM efficiency
  # Horizontal resolution and FOV to mimic camera (~73 deg horizontal FOV)
  lidar_hres: 2.0 # Increased from 1.0 to 2.0 for VRAM efficiency (180 beams around)
  lidar_hfov_deg: 73

# Stereo camera physical specs (for future integration)
stereo:
  cmos_size_inch: "1/4"
  focal_length_mm: 2.6
  aov_deg:
    diagonal: 83
    horizontal: 73
    vertical: 50
  distortion: "<1%"
  baseline_mm: 60
  