algo:
  feature_extractor:
    learning_rate: 5e-4  # Reduced to 5e-4 for very stable learning over 10 hours
    dyn_obs_num: 5       # Keep this for 5 closest obstacles
  
  actor:
    learning_rate: 5e-4  # Reduced to 5e-4 for very stable learning over 10 hours
    clip_ratio: 0.1
    action_limit: 2.0 # m/s
  
  critic:
    learning_rate: 5e-4  # Reduced to 5e-4 for very stable learning over 10 hours
    clip_ratio: 0.1
  
  entropy_loss_coefficient: 3e-3  # Reduced to 3e-3 for more focused learning over 10 hours
  training_frame_num: 128  # Increased to 128 for very stable learning
  training_epoch_num: 4    # Increased to 4 for thorough policy updates
  num_minibatches: 16      # Increased to 16 for very stable gradient estimates