algo:
  feature_extractor:
    learning_rate: 1e-3  # Adjusted back to 1e-3 for stable learning over 1 hour
    dyn_obs_num: 5       # Keep this for 5 closest obstacles
  
  actor:
    learning_rate: 1e-3  # Adjusted back to 1e-3 for stable learning over 1 hour
    clip_ratio: 0.1
    action_limit: 2.0 # m/s
  
  critic:
    learning_rate: 1e-3  # Adjusted back to 1e-3 for stable learning over 1 hour
    clip_ratio: 0.1
  
  entropy_loss_coefficient: 5e-3  # Adjusted back to 5e-3 for balanced exploration
  training_frame_num: 64   # Increased back to 64 for better learning stability
  training_epoch_num: 2    # Increased back to 2 for better policy updates
  num_minibatches: 8       # Increased back to 8 for better gradient estimates