algo:
  feature_extractor:
    learning_rate: 2e-3  # Changed from 1e-3 to 2e-3 for faster learning
    dyn_obs_num: 5       # Keep this for 5 closest obstacles
  
  actor:
    learning_rate: 2e-3  # Changed from 1e-3 to 2e-3 for faster learning
    clip_ratio: 0.1
    action_limit: 2.0 # m/s
  
  critic:
    learning_rate: 2e-3  # Changed from 1e-3 to 2e-3 for faster learning
    clip_ratio: 0.1
  
  entropy_loss_coefficient: 1e-2  # Changed from 5e-3 to 1e-2 for more exploration
  training_frame_num: 32   # Changed from 64 to 32 for faster training steps
  training_epoch_num: 1    # Changed from 2 to 1 for fastest training
  num_minibatches: 4       # Changed from 8 to 4 for faster processing