algo:
  feature_extractor:
    learning_rate: 5e-4  # Keep stable learning rate for 10 hours
    dyn_obs_num: 8       # Increased from 5 to 8 for more obstacle tracking
    hidden_size: 512      # Increased hidden size for more complex features
  
  actor:
    learning_rate: 5e-4  # Keep stable learning rate for 10 hours
    clip_ratio: 0.1
    action_limit: 2.5    # Increased action limit for more dynamic movement
    hidden_size: 512     # Increased hidden size for more complex policy
  
  critic:
    learning_rate: 5e-4  # Keep stable learning rate for 10 hours
    clip_ratio: 0.1
    hidden_size: 512     # Increased hidden size for more complex value function
  
  entropy_loss_coefficient: 2e-3  # Reduced for more focused learning with larger batches
  training_frame_num: 256  # Increased to 256 for maximum GPU utilization
  training_epoch_num: 6    # Increased to 6 for thorough policy updates
  num_minibatches: 32      # Increased to 32 for maximum parallel processing