defaults:
  - _self_
  - drone
  - ppo
  - sim

headless: False  # Make sure visual rendering is enabled
device: "cuda:0"
seed: 101

# Total Training Length - Optimized for extended training duration
max_frame_num: 120000000  # Doubled from 60M to 120M frames for extended training
eval_interval: 300000     # Evaluate every 300K frames (every ~18 minutes)
save_interval: 600000     # Save every 600K frames (every ~36 minutes)

# Training Environment - Optimized for 6-hour training duration
env:
  num_envs: 750          # Keep 750 drones for stability
  max_episode_length: 400  # Increased from 250 to 400 for longer episodes
  env_spacing: 22.0      # Keep spacing for stability
  num_obstacles: 60      # Keep obstacles for stability
  hover_assistance: False

env_dyn:
  num_obstacles: 10      # Reduced for simpler training
  vel_range: [0.5, 1.8]  # Keep velocity range for stability
  local_range: [6.0, 6.0, 5.0]  # Keep local range for stability

viewer:
  eye: [18., 18., 18.]   # Keep view distance for performance
  lookat: [0., 0., 2.]
  resolution: [1600, 900]  # Keep resolution for stability
  
logger:
  backend: tensorboard  # or "csv"
  log_dir: logs
  exp_name: NavRL_750drones_extended
