defaults:
  - _self_
  - drone
  - ppo
  - sim

headless: False  # Make sure visual rendering is enabled
device: "cuda:0"
seed: 101

# Total Training Length
max_frame_num: 12e8 # max frame 
eval_interval: 1000 # evaluate the policy for every N training steps
save_interval: 1000

# Training Environment
# Training Environment
env:
  num_envs: 20        # Changed from 9 to 20 drones
  max_episode_length: 500  # Changed from 2200 to 500 for faster episodes
  env_spacing: 25.0   # Changed from 15.0 to 25.0 for better 20-drone + 120-obstacle spacing
  num_obstacles: 40   # Changed from 8 to 40 static obstacles
  hover_assistance: False  # Changed from True to False (no artificial assistance)

env_dyn:
  num_obstacles: 80   # Changed from 5 to 80 dynamic obstacles
  vel_range: [0.5, 1.5]
  local_range: [5.0, 5.0, 4.5]

viewer:
  eye: [15., 15., 15.]   # Changed from [8., 8., 8.] for better view of crowded environment
  lookat: [0., 0., 2.]
  resolution: [1280, 720]
  
logger:
  backend: tensorboard  # or "csv"
  log_dir: logs
  exp_name: NavRL
