defaults:
  - _self_
  - drone
  - ppo
  - sim

headless: False  # Make sure visual rendering is enabled
device: "cuda:0"
seed: 101

# Total Training Length - Optimized for full resource utilization
max_frame_num: 10000000  # Keep 10M frames for ~10 hours training
eval_interval: 50000      # Evaluate every 50K frames (every ~30 minutes)
save_interval: 100000     # Save every 100K frames (every ~1 hour)

# Training Environment - Optimized for full resource utilization
env:
  num_envs: 1000         # Increased to 1000 drones to utilize full VRAM (16GB)
  max_episode_length: 300  # Increased to 300 for more complex episodes
  env_spacing: 20.0      # Reduced spacing to fit more environments
  num_obstacles: 80      # Increased to 80 static obstacles for full challenge
  hover_assistance: False

env_dyn:
  num_obstacles: 120     # Increased to 120 dynamic obstacles for full resource utilization
  vel_range: [0.5, 2.0]  # Increased velocity range for more dynamic scenarios
  local_range: [8.0, 8.0, 6.0]  # Increased local range for more complex interactions

viewer:
  eye: [20., 20., 20.]   # Increased view distance for 1000 drones
  lookat: [0., 0., 2.]
  resolution: [1920, 1080]  # Increased to 1080p for better monitoring
  
logger:
  backend: tensorboard  # or "csv"
  log_dir: logs
  exp_name: NavRL_1000drones_fullpower
