defaults:
  - _self_
  - drone
  - ppo
  - sim

headless: False  # Make sure visual rendering is enabled
device: "cuda:0"
seed: 0

# Total Training Length
max_frame_num: 12e8 # max frame 
eval_interval: 1000 # evaluate the policy for every N training steps
save_interval: 1000

# Training Environment
env:
  num_envs: 9 # Start with 9 environments (3x3 grid = easy to see all drones)
  max_episode_length: 2200
  env_spacing: 10.0  # Wide spacing so you can see each drone clearly
  num_obstacles: 0   # NO obstacles - pure drone visibility
  hover_assistance: True  # Enable hover assistance for untrained policies

env_dyn:
  num_obstacles: 0  # Zero dynamic obstacles for maximum drone visibility
  vel_range: [0.5, 1.5]
  local_range: [5.0, 5.0, 4.5]

viewer:
  eye: [8., 8., 8.]    # Very close view - should definitely see drones
  lookat: [0., 0., 2.]  # Looking directly at center drone
  resolution: [1920, 1080]  # High resolution for clarity

logger:
  backend: tensorboard  # or "csv"
  log_dir: logs
  exp_name: NavRL
