defaults:
  - _self_
  - drone
  - ppo
  - sim

headless: False  # Make sure visual rendering is enabled
device: "cuda:0"
seed: 101

# Total Training Length - Optimized for 50M frames
max_frame_num: 50000000  # Set to 50M frames as requested
eval_interval: 250000     # Evaluate every 250K frames (every ~15 minutes)
save_interval: 500000     # Save every 500K frames (every ~30 minutes)

# Training Environment - Optimized for stability and performance
env:
  num_envs: 450          # Reduced from 500 to 450 (~10% less VRAM)
  max_episode_length: 300  # Keep 300 for better FPS
  env_spacing: 22.0      # Keep spacing for stability
  num_obstacles: 45      # Reduced from 50 to 45 for VRAM efficiency
  hover_assistance: False

env_dyn:
  num_obstacles: 60      # Reduced from 70 to 60 for VRAM efficiency
  vel_range: [0.5, 1.8]  # Keep velocity range for stability
  local_range: [6.0, 6.0, 5.0]  # Keep local range for stability

viewer:
  eye: [18., 18., 18.]
  lookat: [0., 0., 2.]
  resolution: [1280, 720]
  
logger:
  backend: tensorboard  # or "csv"
  log_dir: logs
  exp_name: NavRL_450drones_50M_vram10less


curriculum:
  enabled: true
  min_goal_dist: 4.0
  max_goal_dist: 24.0
  warmup_resets: 20000
